### ISSUE TITLE
Can not get it to load config files.

### ISSUE THREAD

**Issue by Nodens-** [Microsoft/VisualStudioUninstaller#10]
No to mention that the syntax is missing from the readme but executing "load" or "load config file name" (the later with or without extension) only outputs "Object reference not set to an instance of an object."

**Comment by zetto-saika** [comment]
Here it outputs a success message, but the list commands says nothing was loaded.

**Comment by alphaleonis** [comment]
I copied the DataFiles directory to the My Documents folder, and then it loaded them correctly.

**Comment by unitycoder** [comment]
Copying DataFiles/ folder to Documents/ folder fixed it here also

**Comment by Nodens-** [comment]
Of course the files had been copied to Documents/Datafiles when I reported this. Perhaps this got fixed since it was reported without comment on the issue? I'll pull, try again and report.

**Comment by Nodens-** [comment]
Ok now they load properly. I see some commits related but no comment on this issue. Specifically my repo had .xml Datafiles (although they were not xml upon inspection they were clearly binary). Now the files have .bin extension and there's also a commit regarding loading errors. I am closing this though since they are now loading properly.
