### ISSUE TITLE
How can i open the setup?can't find a way to open admini....

### ISSUE THREAD

**Issue by AlexhahDeng** [Microsoft/VisualStudioUninstaller#102]
i have tried several ways to open administrator command prompt but failed, could someone tell me how to do that in win10?

**Comment by heaths** [comment]
The following workflow works on Windows Vista and newer, including Windows 10:

1. Click on **Start**
2. Type: Command Prompt
3. Right-click on **Command Prompt**
4. Click **Run as Administrator**
