### ISSUE TITLE
SQL Server Management Studio 2016

### ISSUE THREAD

**Issue by TLOD** [Microsoft/VisualStudioUninstaller#103]
SQL Server Management Studio 2016 does not work after running VisualStudioUninstaller Release 5

**Comment by heaths** [comment]
Some packages shared with SSMS may have been removed. You need to repair SSMS to restore functionality, as well as any other editions of Visual Studio.

**Comment by victorvartan** [comment]
Just want to add that unfortunately even SQL Server Management Studio (SSMS) 17.X is based on the Visual Studio 2015 Isolated shell, so don't uninstall VS2015 if you need SSMS on the same machine...
