### ISSUE TITLE
How to run this silent?

### ISSUE THREAD

**Issue by dinocizmic** [Microsoft/VisualStudioUninstaller#109]
I need to run this silently, is there any switch that I can use to not need to enter in the 'y'?

**Comment by heaths** [comment]
Note that this is a latch resort if normal uninstall isn't working - nothing something to be automated as a normal use case. As such, we don't support silent execution.

You can, however, echo "y" via pipe to any command asking for "y" or "n" that runs in a console.

**Comment by dinocizmic** [comment]
How would I do a normal uninstall with removing all other programs that VS installed?

**Comment by heaths** [comment]
Visual Studio doesn't remove most other applications it installed, especially if other installers and those packages use package ref-counting. The VisualStudioUninstaller does even less checks as its a last resort sort of program.
