### ISSUE TITLE
Datafile for vs community 2015 update 1?

### ISSUE THREAD

**Issue by unitycoder** [Microsoft/VisualStudioUninstaller#16]
There is "Microsoft Visual Studio Community 2015.bin",
not sure if can use with 2015 update 1 also?

**Comment by alexmajor** [comment]
+1

**Comment by hulucc** [comment]
+1

**Comment by giacgbj** [comment]
+1

**Comment by ziriax** [comment]
+1

**Comment by tobyhu87** [comment]
@unitycoder  Thank you for reporting this issue. The latest drop of Uninstaller knows all public releases of Visual Studio 2013 and above.  It should be able to detect the Community 2015 Update 1 and uninstall it from your system.  

Release link: https://github.com/Microsoft/VisualStudioUninstaller/releases
