### ISSUE TITLE
Instructions on how to create a .BIN datafile

### ISSUE THREAD

**Issue by earaya** [Microsoft/VisualStudioUninstaller#17]
I have a SKU that's not currently in the DataFiles folder. The tools shows an option on creating one, but there are no instructions on how to do so.

Please instruct on how to do create custom .BIN files for other SKUs.

**Comment by tobyhu87** [comment]
@earaya The latest drop of the Uninstall no longer requires .BIN file.  The application contains a master list of Bundle IDs and upgrade codes for every MSI ever chained in by Visual Studio 2013-vNext.

Release link: https://github.com/Microsoft/VisualStudioUninstaller/releases
