### ISSUE TITLE
VisualStudioUninstaller doesn't work

### ISSUE THREAD

**Issue by Immick** [Microsoft/VisualStudioUninstaller#19]
Hello!

I've uninstalled VS 2013 Ultimate Upd 5 but the size of the folder "Microsoft Visual Studio 12.0" was about 2 GB. So I decided to use VisualStudioUninstaller . I followed by the instructions:
1. _DIR_ to *.bin files folder
2. _LOAD_
3. _LIST_ 
   ![listresults](https://cloud.githubusercontent.com/assets/12298761/12148537/11203ed0-b4b0-11e5-91f5-7e0038d4770d.png)
4. _SELECT_: 10 - "Microsoft Visual Studio Ultimate 2013 with Update 5"
5. _UNISTALL_

And after the step 5 (UNISTALL) I got the message "MSI batch uninstall completed successfully" - and that's all - nothing happened (at all) - there was no uninstallation process or something.

So what I made wrong?

Thank you!
!

**Comment by bgacek** [comment]
+1

**Comment by me-on-gh** [comment]
+1 Same here

**Comment by alaptiko** [comment]
+1. Nothing happens but I selected some bundles:
![list](https://cloud.githubusercontent.com/assets/1449733/12884610/1885fd78-ce68-11e5-8f10-11c07e26642f.png)
And after `UNINSTALL` command it outputs: `MSI batch uninstall completed successfully`
I have installed vs2010 and vs2015 and trying to delete vs2013 leftovers and vs2015.

**Comment by tobyhu87** [comment]
@Immick The latest drop of the Uninstaller will no longer ask so many questions.  It will only ask you if you really want to uninstall Visual Studio.  You can try it here: https://github.com/Microsoft/VisualStudioUninstaller/releases
