### ISSUE TITLE
Problem to run project

### ISSUE THREAD

**Issue by felipejdias** [Microsoft/VisualStudioUninstaller#2]
Hi, I have tried to run this project and I get an error. I try to run it, with following steps
1. Open Uninstaller.sln on Visual Studio Ultimate 2013
2. Build the solution
3. Run the project "Unistall_Wrapper" in Visual Studio
4. Execute the "Setup.ForcedUninstall.exe" file in output directory of build.

In all of my tentatives to run it i get similar error, I have attached the messege, please, could you help me if I made some mistakes or not?

![unistall_vs2](https://cloud.githubusercontent.com/assets/12104201/10617717/afadf1d0-774a-11e5-9874-0e8b0f5ed15c.jpg)
![unistall_vs1](https://cloud.githubusercontent.com/assets/12104201/10617718/afbf94a8-774a-11e5-9abd-1292180ad81e.jpg)

**Comment by heaths** [comment]
The private key is not part of the repo. You will need to disable strong name verification for that public key token:

```
sn.exe -Vr *,b03f5f7f11d50a3a
```

**Comment by felipejdias** [comment]
Thanks for your prompt reply. I cannot execute this command but I see you have a new commit that disable this validation. Thanks very much.
