### ISSUE TITLE
Putting quotes around DIR path breaks it

### ISSUE THREAD

**Issue by CADbloke** [Microsoft/VisualStudioUninstaller#20]
Error message: `Caller: CheckInvalidPathChars  Msg: Illegal characters in path.`

I thought it was because the path had a dot in it but it works without the dot. 

The path ... `C:\Codez\z.Github\VisualStudioUninstaller\DataFiles` .. worked ok without quotes. I didn't try a path with a space in it.

**Comment by tobyhu87** [comment]
@CADbloke The latest drop of the tool has less user interaction, it will now only ask you if you really want to uninstall Visual Studio.  There's no more complicated user interactions between the user and the application.

Release link: https://github.com/Microsoft/VisualStudioUninstaller/releases
