### ISSUE TITLE
Instructions need testing on real users

### ISSUE THREAD

**Issue by CADbloke** [Microsoft/VisualStudioUninstaller#21]
First and foremost, thanks for writing this. This is somewhat cheeky but I hope you grok my intention, the instructions just need some feedback from a user with less experience in this sort of thing than the people who have commit rights to this repo.
### Using Total Uninstall:

> The  user identifies which SKU of which release he wants to uninstall.

No girls allowed. Also, translation: Figure out which version of which Visual Studio you want to uninstall. The `DataFiles` folder lists the ones you should be looking for. If it's not listed then don't look for it. This will not uninstall your mother-in-law nor VS2005 from your 386 which has been corporate-firewalled from the modern world nearly as effectively has you have.

> The  user downloads one or more data files (from DataFiles folder) to a local folder.

If the user has somehow managed to clone this repo to a folder that is not local (_well done!_) then the user will need to download them by ...er, cloning this repo to a local folder. Perhaps this instruction refers to a user who has downloaded a pre-compiled build which, of of writing, does not exist.

> The user executes Total Uninstaller and then dir to the directory containing the config files.

It's actually called `Setup.ForcedUninstall.exe`. Remember that local repo we were talking about? `DIR` the `DataFiles` folder. Don't out quotes around the path because #20 

> The user executes load command to the config files.

~~I skipped that step and it didn't seem to matter.~~ YES, it does. do it.

> The user executes list to show which SKU and release is selected and installed.

~~See, it didn't matter.~~  Sh'up fool, it matters.

> The user executes select to select which SKU, release, version he wants to uninstall.

Again, sorry ladies, **no uninstall for you!**

> The user executes uninstall to perform the total uninstall.

**Comment by tobyhu87** [comment]
@CADbloke Thank you for comments and suggestions.

The latest drop of the tool is more usable.  All these unnecessary user interactions are gone.  It'll simply ask you confirm if you want to uninstall Visual Studio and nothing more.  And it knows how to uninstall Visual Studio 2013 and later.  

Feel free to give the prebuilt binaries a try here:
Release link: https://github.com/Microsoft/VisualStudioUninstaller/releases
