### ISSUE TITLE
'Setup.ForcedUninstall.exe' is not recognized

### ISSUE THREAD

**Issue by k-williams** [Microsoft/VisualStudioUninstaller#28]
When I run
`C:\Windows\system32>Setup.ForcedUninstall.exe`
the output is

```
'Setup.ForcedUninstall.exe' is not recognized as an internal or external command
,
operable program or batch file
```

**Comment by iamthegD** [comment]
Even more funny is this comes at 4h20. Progran u r tryong to exec is not on
that path.

**Comment by denizdogan** [comment]
You need to `cd` to the directory where `Setup.ForcedUninstall.exe` is located first.

**Comment by AbeKline** [comment]
Where should I find `Setup.ForcedUninstall.exe`?

**Comment by tobyhu87** [comment]
You can download the pre-built drop here:  https://github.com/Microsoft/VisualStudioUninstaller/releases 

The binaries are in the unzipped folder.

**Comment by SebastianAsprilla** [comment]
![image](https://cloud.githubusercontent.com/assets/25800080/22986852/d4c8f4ee-f37a-11e6-8849-fe3f4e7a97e8.png)
where the space is your Local folder "usually is the registered name for your computer"
