### ISSUE TITLE
Where's the .exe for when we don't have VS installed anymore!?

### ISSUE THREAD

**Issue by abukres** [Microsoft/VisualStudioUninstaller#33]
I don't have VS installed anymore to compile this source. The point of this utility is to remove all traces of it after a botched uninstall. Right?

**Comment by Planet99** [comment]
I uninstalled VS 2015 from my D drive cause the C ssd was full when I first installed. Got a bigger ssd and uninstalled vs 2015 (Update 2 broke it anyway) and the installer will not let me install to C.  WTF. Where is the installer getting that folder name from !!!!!!!! I deleted that folder and its references in the reg cause the folder doesn't exist anymore. Obviously the uninstall /force did not do very much. I want the thing really uninstalled - not just pretend uninstalled - but there are remnants that I have no idea where they are. Come on MS - when is an uninstall not an uninstall. And like @abukres - where is the binary. The blog explicitly states it is here and it is not here.

The point of this utility is to remove all traces of it after a very very botched uninstall. Right?

**Comment by Planet99** [comment]
Its in releases

**Comment by tobyhu87** [comment]
Hi folks,

Please go to the release page for the pre-built binaries.  You can find it here: https://github.com/Microsoft/VisualStudioUninstaller/releases/tag/v1.2 

thanks
toby

**Comment by Planet99** [comment]
Thanks for the response.

After running this tool several times I still can't install VS2015 to my C drive. The location in the installer is the non-editable non-existent old folder from D. Do you know by any chance where the installer is pulling this from so I can put VS on my SSD.

Thanks
9

**Comment by Planet99** [comment]
For future reference: I ran procmon on vs_professional.exe and searched for the rouge path name. Was still embedded in registry entries that had to be meaningless since that folder does not exist. Deleted them and now I own my machine again. Yea.

Thanks

**Comment by ghost** [comment]
Issue should be closed.
