### ISSUE TITLE
Visual Studio Ultimate 2015 still blocking new installation

### ISSUE THREAD

**Issue by arbrown** [Microsoft/VisualStudioUninstaller#40]
Several months ago my VS Ultimate 2015 ultimate became borked (I think maybe something to do with ReSharper) and in the process of trying to uninstall it, I left it in a terribly broken state.  Now I am trying to install VS Community 2015 and it refuses to install, claiming that the old version is still there.  I have _no_ idea what it is detecting to block the installation (definitely no executables, and I can't find any references to it in the registry) but somehow the installer thinks there is a vestige of VS Ultimate 2015 and this uninstaller tool doesn't know how to remove it.

I'd be happy to provide log files or any additional information if that would help.  I'm really at my wits' end here.

**Comment by tobyhu87** [comment]
Yes, if you could send me the logs, that would be great.

You can use our collect tool: https://www.microsoft.com/en-us/download/details.aspx?id=12493 

Please download the Collect.exe, and run the Collect.exe under cmd.exe .  The collect tool will zip up the logs to %temp%/vslogs.zip (in your temp folder).  You can just email me that zip file.

thanks
toby.

**Comment by TranquilMarmot** [comment]
Just ran into this as well; the registry key the Visual Studio 2015 Community Edition installer looks for is `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\DevDiv\vs\Servicing\14.0\ultimate` (if you didn't have a 64-bit installation, ignore the `WOW6432Node` bit)

I was able to get the Community installer working after removing that registry folder. Unfortunately, launching Community launches as Ultimate edition still (I was trying to get Community because my license had expired)

**Comment by arbrown** [comment]
@TranquilMarmot Good catch, I hadn't seen that folder in the registry before.  I deleted it and installed community edition, but like you, it still thinks that it's launching ultimate and demands a key.  I definitely used the community edition installer, and there were no ultimate binaries or other files (that I know of on the system.)  This is truly infuriating.

**Comment by arbrown** [comment]
@TranquilMarmot I was able to get it to work at last!  I used the add/remove programs feature in the control panel to _repair_ Visual Studio 2015.  It took quite a long time (who knows why) and this time it asked me to restart my computer at the end.  When I did, I started up Visual Studio Blend and signed in with my Microsoft account.  That worked, and regular Visual Studio did as well.  I'm guessing the repair fixed it, but I thought I'd mention my exact steps.  Hopefully you can get it up and running for yourself.

Also, this project probably ought to delete the registry key that Marmot mentioned above.  That was crucial for getting my situation fixed.

**Comment by TranquilMarmot** [comment]
@arbrown literally did the same thing last night and got it working, very cool 😎

**Comment by TranquilMarmot** [comment]
Also, for anyone else looking, the registry key will have a different name based on what old version of Visual Studio you had installed, so `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\DevDiv\vs\Servicing\14.0\ultimate` for ultimate, and `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\DevDiv\vs\Servicing\14.0\enterprise` for enterprise,
etc

**Comment by tobyhu87** [comment]
Thank you guys, I have updated the Uninstaller to remove these registries as well.  I will close this issue as soon as the binaries are available.

**Comment by tobyhu87** [comment]
This issue is fixed in https://github.com/Microsoft/VisualStudioUninstaller/releases/tag/v1.4

**Comment by Zabee** [comment]
Believe me, the solution from @TranquilMarmot still works in 2018. Thank you.
