### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by ghost** [Microsoft/VisualStudioUninstaller#46]
Running it multiple times as admin, it consistently says uninstall VS 2015 SDK with exit code 1603

I can run it 10 times, every time it leaves 12 items as the output below shows.
It does that for 12 more items, all fail.

Fresh reboot, no VS running processes...
No bundle found.  Uninstalling stale MSIs.
WARNING: This executable is designed to cleanup/scorch all Preview/RC/RTM releases of Visual Studio 2013, Visual Studio 20
It should be used as the last resort to clean up the user's system before resorting to reimaging the machine.
Would you like to continue? [Y/N]
y
Normal Visual Studio Uninstall completed.
Searching for stale MSIs and clean up stale MSIs.
12 stale MSIs found.  Uninstalling them.
Uninstalled MS ASP.NET MVC 4 - Visual Studio 2015 - ENU with exit code: 1603. 11/12
Uninstalled MS ASP.NET Web Pages 2 - Visual Studio 2015 - ENU with exit code: 1603. 10/12
Uninstalled Test Tools for VS 2015 with exit code: 1603. 9/12
Uninstalled Visual Studio 2015 Prerequisites with exit code: 1603. 8/12
Uninstalled VS 2015 Devenv with exit code: 1603. 7/12
Uninstalled VS 2015 Performance Collection Tools with exit code: 1603. 6/12
Uninstalled VS 2015 SDK - ENU with exit code: 1603. 5/12
Uninstalled VS 2015 Shell (Minimum) with exit code: 1603. 4/12
Uninstalled VS Community 2015 with exit code: 1603. 3/12
Uninstalled VS Enterprise 2015 with exit code: 1603. 2/12
Uninstalled VS Premium 2015 with exit code: 1603. 1/12
Uninstalled VS Professional 2015 with exit code: 1603. 0/12

**Comment by abhishekns** [comment]
Similar error code. 
Microsoft Visual Studio Enterprise 2015, still shows as installed in the "Programs And Features".

# 

The following bundles were detected on your system:
(Name: Microsoft Visual Studio Enterprise 2015, Version: 14.0.23107.178, BundleId: aaff6d8c-30d0-4446-82ae-1f1650eab4b9)
WARNING: This executable is designed to cleanup/scorch all Preview/RC/RTM releases of Visual Studio 2013, Visual Studio 2015 and Visual Stud
io vNext.
It should be used as the last resort to clean up the user's system before resorting to reimaging the machine.
Would you like to continue? [Y/N]
Y
Uninstalling: C:\ProgramData\Package Cache{aaff6d8c-30d0-4446-82ae-1f1650eab4b9}\vs_enterprise.exe
Bundle: Microsoft Visual Studio Enterprise 2015 has been uninstalled with exit code: 1603.
Normal Visual Studio Uninstall completed.
Searching for stale MSIs and clean up stale MSIs.
Deleting: C:\ProgramData\Microsoft\VisualStudioSecondaryInstaller
Deleting registry: SOFTWARE\Microsoft\VisualStudio\12.0
Deleting registry: SOFTWARE\Microsoft\VisualStudio\14.0
Deleting registry: SOFTWARE\Microsoft\VisualStudio\15.0
Deleting registry: SOFTWARE\Microsoft\VisualStudio\12.0_Config
Deleting registry: SOFTWARE\Microsoft\VisualStudio\14.0_Config
Deleting registry: SOFTWARE\Microsoft\VisualStudio\15.0_Config
Deleting registry: SOFTWARE\Microsoft\DevDiv\vs\Servicing\12.0
Deleting registry: SOFTWARE\Microsoft\DevDiv\vs\Servicing\14.0
Deleting registry: SOFTWARE\Microsoft\DevDiv\vs\Servicing\15.0

**Comment by WilliamHCPowell** [comment]
And similar here, "Microsoft Visual Studio Community 2015 with Updates" version 14.0.25420.1, using release 5 of the tool:
I ran the Setup.ForcedUninstall.exe first from a PowerShell and then from a CMD Administrator prompt.  The number of stale MSIs went down from 30 to 26, but the output was broadly similar, being peppered with 1603 exit codes and the VS Community 2015 still showing up in Programs and Features.

Detailed output from run 1 (powershell)

Windows PowerShell
Copyright (C) 2014 Microsoft Corporation. All rights reserved.

PS C:\Windows\system32> cd C:\Users\Bill\Downloads
PS C:\Users\Bill\Downloads> explorer .
PS C:\Users\Bill\Downloads> cd .\TotalUninstaller
PS C:\Users\Bill\Downloads\TotalUninstaller> dir


    Directory: C:\Users\Bill\Downloads\TotalUninstaller


Mode                LastWriteTime     Length Name
----                -------------     ------ ----
d----        27/11/2016     11:09            TotalUninstaller


PS C:\Users\Bill\Downloads\TotalUninstaller> cd .\TotalUninstaller
PS C:\Users\Bill\Downloads\TotalUninstaller\TotalUninstaller> .\Setup.ForcedUninstall.exe
The following bundles were detected on your system:
(Name: Microsoft Visual Studio Community 2015 with Updates, Version: 14.0.25420.1, BundleId: 79b486b9-c5f0-4096-a00c-8351f59587c2)
WARNING: This executable is designed to cleanup/scorch all Preview/RC/RTM releases of Visual Studio 2013, Visual Studio 2015 and Visual Studio vNext.
It should be used as the last resort to clean up the user's system before resorting to reimaging the machine.
Would you like to continue? [Y/N]
y
Uninstalling: C:\ProgramData\Package Cache\{79b486b9-c5f0-4096-a00c-8351f59587c2}\vs_community.exe
Bundle: Microsoft Visual Studio Community 2015 with Updates has been uninstalled with exit code: 1603.
Normal Visual Studio Uninstall completed.
Searching for stale MSIs and clean up stale MSIs.
30 stale MSIs found.  Uninstalling them.
Uninstalled MS .NET Core 5.0 SDK with exit code: 1603. 29/30
Uninstalled MS .NET Framework 4.5 Multi-Targeting Pack with exit code: 1603. 28/30
Uninstalled MS .NET Framework 4.5.1 Multi-Targeting Pack with exit code: 1603. 27/30
Uninstalled MS .NET Framework 4.5.1 RC Multi-Targeting Pack for Windows Store Apps with exit code: 0. 26/30
Uninstalled MS .NET Framework 4.5.1 RC Multi-Targeting Pack for Windows Store Apps (ENU) with exit code: 1603. 25/30
Uninstalled MS .NET Framework 4.5.2 Multi-Targeting Pack with exit code: 1603. 24/30
Uninstalled MS .NET Framework 4.5.2 Multi-Targeting Pack (ENU) with exit code: 0. 23/30
Uninstalled MS .NET Framework 4.6 Targeting Pack with exit code: 1603. 22/30
Uninstalled MS Build Tools 14.0 (amd64) with exit code: 1603. 21/30
Uninstalled MS Build Tools 14.0 (x86) with exit code: 1603. 20/30
Uninstalled MS Build Tools Language Resources 14.0 (amd64) with exit code: 1603. 19/30
Uninstalled MS Build Tools Language Resources 14.0 (x86) with exit code: 1603. 18/30
Uninstalled MS Portable Library Multi-Targeting Pack with exit code: 1603. 17/30
Uninstalled MS Portable Library Multi-Targeting Pack Language Pack - enu with exit code: 1603. 16/30
Uninstalled MS SQL Server 2012 Native Client  with exit code: 0. 15/30
Uninstalled MS SQL Server 2016 LocalDB  with exit code: 0. 14/30
Uninstalled MS SQL Server 2016 Management Objects  with exit code: 0. 13/30
Uninstalled MS SQL Server 2016 Management Objects  (x64) with exit code: 0. 12/30
Uninstalled MS SQL Server 2016 T-SQL Language Service  with exit code: 0. 11/30
Uninstalled MS SQL Server 2016 T-SQL ScriptDom  with exit code: 0. 10/30
Uninstalled MS SQL Server Data Tools - enu (14.0.60519.0) with exit code: 1603. 9/30
Uninstalled MS System CLR Types for SQL Server 2016 with exit code: 0. 8/30
Uninstalled MS System CLR Types for SQL Server 2016 with exit code: 0. 7/30
Uninstalled Prerequisites for SSDT  with exit code: 0. 6/30
Uninstalled VS 2015 Shell (Minimum) with exit code: 1603. 5/30
Uninstalled VS Community 2015 with exit code: 1603. 4/30
Uninstalled VS Community 2015 - ENU with exit code: 1603. 3/30
Uninstalled VS TFS 2015 Update 3 CTP1 Office Integration (x64) with exit code: 0. 2/30
Uninstalled VS TFS 2015 Update 3 CTP1 Storyboarding (x64) with exit code: 0. 1/30
Uninstalled Windows XP Targeting with C++ with exit code: 1603. 0/30
Deleting: C:\ProgramData\Microsoft\VisualStudioSecondaryInstaller
Deleting registry: SOFTWARE\Microsoft\VisualStudio\12.0
Deleting registry: SOFTWARE\Microsoft\VisualStudio\14.0
Deleting registry: SOFTWARE\Microsoft\VisualStudio\15.0
Deleting registry: SOFTWARE\Microsoft\VisualStudio\12.0_Config
Deleting registry: SOFTWARE\Microsoft\VisualStudio\14.0_Config
Deleting registry: SOFTWARE\Microsoft\VisualStudio\15.0_Config
Deleting registry: SOFTWARE\Microsoft\DevDiv\vs\Servicing\12.0
Deleting registry: SOFTWARE\Microsoft\DevDiv\vs\Servicing\14.0
Deleting registry: SOFTWARE\Microsoft\DevDiv\vs\Servicing\15.0
PS C:\Users\Bill\Downloads\TotalUninstaller\TotalUninstaller>

Second run (CMD):

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Windows\system32>cd \Users\Bill\Downloads\TotalUninstaller\TotalUninstaller

C:\Users\Bill\Downloads\TotalUninstaller\TotalUninstaller>Setup.ForcedUninstall.exe
The following bundles were detected on your system:
(Name: Microsoft Visual Studio Community 2015 with Updates, Version: 14.0.25420.1, BundleId: 79b486b9-c5f0-4096-a00c-835
1f59587c2)
WARNING: This executable is designed to cleanup/scorch all Preview/RC/RTM releases of Visual Studio 2013, Visual Studio
2015 and Visual Studio vNext.
It should be used as the last resort to clean up the user's system before resorting to reimaging the machine.
Would you like to continue? [Y/N]
y
Uninstalling: C:\ProgramData\Package Cache\{79b486b9-c5f0-4096-a00c-8351f59587c2}\vs_community.exe
Bundle: Microsoft Visual Studio Community 2015 with Updates has been uninstalled with exit code: 1603.
Normal Visual Studio Uninstall completed.
Searching for stale MSIs and clean up stale MSIs.
26 stale MSIs found.  Uninstalling them.
Uninstalled MS .NET Core 5.0 SDK with exit code: 1603. 25/26
Uninstalled MS .NET Framework 4.5 Multi-Targeting Pack with exit code: 0. 24/26
Uninstalled MS .NET Framework 4.5.1 Multi-Targeting Pack with exit code: 0. 23/26
Uninstalled MS .NET Framework 4.5.1 RC Multi-Targeting Pack for Windows Store Apps (ENU) with exit code: 0. 22/26
Uninstalled MS .NET Framework 4.5.2 Multi-Targeting Pack with exit code: 0. 21/26
Uninstalled MS .NET Framework 4.6 Targeting Pack with exit code: 1603. 20/26
Uninstalled MS Build Tools 14.0 (amd64) with exit code: 0. 19/26
Uninstalled MS Build Tools 14.0 (x86) with exit code: 0. 18/26
Uninstalled MS Build Tools Language Resources 14.0 (amd64) with exit code: 1603. 17/26
Uninstalled MS Build Tools Language Resources 14.0 (x86) with exit code: 1603. 16/26
Uninstalled MS Portable Library Multi-Targeting Pack with exit code: 1603. 15/26
Uninstalled MS Portable Library Multi-Targeting Pack Language Pack - enu with exit code: 1603. 14/26
Uninstalled MS SQL Server 2012 Native Client  with exit code: 0. 13/26
Uninstalled MS SQL Server 2016 LocalDB  with exit code: 0. 12/26
Uninstalled MS SQL Server 2016 Management Objects  with exit code: 0. 11/26
Uninstalled MS SQL Server 2016 Management Objects  (x64) with exit code: 0. 10/26
Uninstalled MS SQL Server 2016 T-SQL Language Service  with exit code: 0. 9/26
Uninstalled MS SQL Server 2016 T-SQL ScriptDom  with exit code: 0. 8/26
Uninstalled MS SQL Server Data Tools - enu (14.0.60519.0) with exit code: 0. 7/26
Uninstalled MS System CLR Types for SQL Server 2016 with exit code: 0. 6/26
Uninstalled MS System CLR Types for SQL Server 2016 with exit code: 0. 5/26
Uninstalled Prerequisites for SSDT  with exit code: 0. 4/26
Uninstalled VS 2015 Shell (Minimum) with exit code: 1603. 3/26
Uninstalled VS Community 2015 with exit code: 1603. 2/26
Uninstalled VS Community 2015 - ENU with exit code: 1603. 1/26
Uninstalled Windows XP Targeting with C++ with exit code: 1603. 0/26
Deleting: C:\ProgramData\Microsoft\VisualStudioSecondaryInstaller
Deleting registry: SOFTWARE\Microsoft\VisualStudio\12.0
Deleting registry: SOFTWARE\Microsoft\VisualStudio\14.0
Deleting registry: SOFTWARE\Microsoft\VisualStudio\15.0
Deleting registry: SOFTWARE\Microsoft\VisualStudio\12.0_Config
Deleting registry: SOFTWARE\Microsoft\VisualStudio\14.0_Config
Deleting registry: SOFTWARE\Microsoft\VisualStudio\15.0_Config
Deleting registry: SOFTWARE\Microsoft\DevDiv\vs\Servicing\12.0
Deleting registry: SOFTWARE\Microsoft\DevDiv\vs\Servicing\14.0
Deleting registry: SOFTWARE\Microsoft\DevDiv\vs\Servicing\15.0

C:\Users\Bill\Downloads\TotalUninstaller\TotalUninstaller>

**Comment by WilliamHCPowell** [comment]
It eventually worked!

I kept repeating the Setup.ForcedUninstall.exe command, and each time the 
"26 stale MSIs found. Uninstalling them."
count decreased.  One by one the 1603 codes converted to 0 codes (17, then 14, 10, 9, 7, 6, 4, 3, 2 , until there was just one left, that wouldn't go away.  The log showed:

Uninstalling: C:\ProgramData\Package Cache\{79b486b9-c5f0-4096-a00c-8351f59587c2}\vs_community.exe
Bundle: Microsoft Visual Studio Community 2015 with Updates has been uninstalled with exit code: 1603.
Normal Visual Studio Uninstall completed.
Searching for stale MSIs and clean up stale MSIs.
1 stale MSIs found.  Uninstalling them.
Uninstalled VS Community 2015 - ENU with exit code: 1603. 0/1
Deleting: C:\ProgramData\Microsoft\VisualStudioSecondaryInstaller
Cannot delete Secondary Installer cache with error: The directory is not empty.

Inspecting the folder, it appeared empty, so I surmised that a reboot would close off any still-open handles, and/or let Windows delete any files marked for deletion on reboot.

Post-reboot, two more runs finally got rid of the last debris:
Windows PowerShell
Copyright (C) 2014 Microsoft Corporation. All rights reserved.

PS C:\Windows\system32> cd C:\Users\Bill\Downloads\TotalUninstaller\TotalUninstaller
PS C:\Users\Bill\Downloads\TotalUninstaller\TotalUninstaller> .\Setup.ForcedUninstall.exe
The following bundles were detected on your system:
(Name: Microsoft Visual Studio Community 2015 with Updates, Version: 14.0.25420.1, BundleId: 79b486b9-c5f0-4096-a00c-8351f59587c2)
WARNING: This executable is designed to cleanup/scorch all Preview/RC/RTM releases of Visual Studio 2013, Visual Studio 2015 and Visual Studio vNext.
It should be used as the last resort to clean up the user's system before resorting to reimaging the machine.
Would you like to continue? [Y/N]
Y
Uninstalling: C:\ProgramData\Package Cache\{79b486b9-c5f0-4096-a00c-8351f59587c2}\vs_community.exe
Bundle: Microsoft Visual Studio Community 2015 with Updates has been uninstalled with exit code: 1603.
Normal Visual Studio Uninstall completed.
Searching for stale MSIs and clean up stale MSIs.
1 stale MSIs found.  Uninstalling them.
Uninstalled VS Community 2015 - ENU with exit code: 1603. 0/1
Deleting: C:\ProgramData\Microsoft\VisualStudioSecondaryInstaller
Deleting registry: SOFTWARE\Microsoft\VisualStudio\12.0
Deleting registry: SOFTWARE\Microsoft\VisualStudio\14.0
Deleting registry: SOFTWARE\Microsoft\VisualStudio\15.0
Deleting registry: SOFTWARE\Microsoft\VisualStudio\12.0_Config
Deleting registry: SOFTWARE\Microsoft\VisualStudio\14.0_Config
Deleting registry: SOFTWARE\Microsoft\VisualStudio\15.0_Config
Deleting registry: SOFTWARE\Microsoft\DevDiv\vs\Servicing\12.0
Deleting registry: SOFTWARE\Microsoft\DevDiv\vs\Servicing\14.0
Deleting registry: SOFTWARE\Microsoft\DevDiv\vs\Servicing\15.0
PS C:\Users\Bill\Downloads\TotalUninstaller\TotalUninstaller> .\Setup.ForcedUninstall.exe
The following bundles were detected on your system:
(Name: Microsoft Visual Studio Community 2015 with Updates, Version: 14.0.25420.1, BundleId: 79b486b9-c5f0-4096-a00c-8351f59587c2)
WARNING: This executable is designed to cleanup/scorch all Preview/RC/RTM releases of Visual Studio 2013, Visual Studio 2015 and Visual Studio vNext.
It should be used as the last resort to clean up the user's system before resorting to reimaging the machine.
Would you like to continue? [Y/N]
y
Uninstalling: C:\ProgramData\Package Cache\{79b486b9-c5f0-4096-a00c-8351f59587c2}\vs_community.exe
Bundle: Microsoft Visual Studio Community 2015 with Updates has been uninstalled with exit code: 0.
Normal Visual Studio Uninstall completed.
Searching for stale MSIs and clean up stale MSIs.
Deleting: C:\ProgramData\Microsoft\VisualStudioSecondaryInstaller
Deleting registry: SOFTWARE\Microsoft\VisualStudio\12.0
Deleting registry: SOFTWARE\Microsoft\VisualStudio\14.0
Deleting registry: SOFTWARE\Microsoft\VisualStudio\15.0
Deleting registry: SOFTWARE\Microsoft\VisualStudio\12.0_Config
Deleting registry: SOFTWARE\Microsoft\VisualStudio\14.0_Config
Deleting registry: SOFTWARE\Microsoft\VisualStudio\15.0_Config
Deleting registry: SOFTWARE\Microsoft\DevDiv\vs\Servicing\12.0
Deleting registry: SOFTWARE\Microsoft\DevDiv\vs\Servicing\14.0
Deleting registry: SOFTWARE\Microsoft\DevDiv\vs\Servicing\15.0
PS C:\Users\Bill\Downloads\TotalUninstaller\TotalUninstaller>

Finally, programs and features shows the VS is gone.

Hooray and thank you.  

Next stop - see if I can create a functioning install!
