### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by futagoza** [Microsoft/VisualStudioUninstaller#5]
Is this project working?

I'm not sure if this is working because I'm having problems building any projects in Visual Studio which is why I want to remove it all (I have Visual Studio 2012 - 2015 installed, all Express editions and Community) and start a fresh install of Visual Studio 2015.

**Comment by tobyhu87** [comment]
Hi futagoza,

What build error are you seeing?  We can help you fix the problem.

thanks
toby.

**Comment by futagoza** [comment]
1) Permission writing errors
2) MSBuild Visual Studio version errors

I'm guessing these problems cropped up because I had express edition's of Visual Studio 2010 to Visual Studio 2013 installed, had Visual Studio 2015 Community Edition, and decided to upgrade Windows 8.1 to Windows 10, and then resumed my C++/C# projects 2 months later, only to run into building issues.

I don't want to fix the issues now though, I want to:

1) Remove everything Visual Studio related
2) Install a fresh copy of Visual Studio 2015 Community Edition

I'de do it manually but removing everything one by one is getting tedious, especially when there seems to be so many extra programs its installed, so I gave up after 2 hours and have resumed using Sublime Text, for now :)

**Comment by tobyhu87** [comment]
@futagoza Thank you for reporting this issue.  I had review your issue and made the suggested change to the uninstaller.  You can download and use the pre-built binaries directly.  The usage is now different.  It will no longer ask you to pass in configuration files, etc.  You just run it and it will uninstall Visual Studio for you.

https://github.com/Microsoft/VisualStudioUninstaller/releases
