### ISSUE TITLE
Uninstaller Stuck

### ISSUE THREAD

**Issue by varunsharma27** [Microsoft/VisualStudioUninstaller#50]
![stuck](https://cloud.githubusercontent.com/assets/18154526/18345215/26379e64-75d8-11e6-80bb-7b691f361925.png)

I've been sitting on this screen for around 30 minutes.

S/W : Visual Studio 2013 with Update 2.
O/S : Windows 10

**Comment by tobyhu87** [comment]
Hi sir, 

It is calling into Visual Studio to do a top down un-installation; and that could take a while.  It is one of the feature request to connect the Visual Studio pipe to report progress.  

Unfortunately, I had been really busy with work and didn't have the personal spare time to work on this.

thanks
toby.

**Comment by varunsharma27** [comment]
Dear Toby, 
Thank you very much for entertaining my query. I left the Uninstaller running for 1 hour and it was done by the time I came back. 
Varun
