### ISSUE TITLE
Thank you for this!!!

### ISSUE THREAD

**Issue by knilecrack** [Microsoft/VisualStudioUninstaller#52]
I almost went crazy with visual studio that far that I wanted to smash my computer with hammer. In 1st place I remove it and then when I wanted to install, installer acted like it's installed!!! thank you

**Comment by RobertPaulson90** [comment]
It's kind of you for wanting to say thanks, but you have now opened an "Issue" which really isn't the intended purpose of this feature. It isn't supposed to be a forum.

**Comment by knilecrack** [comment]
delete it
