### ISSUE TITLE
Visual Studio 2017 RC support

### ISSUE THREAD

**Issue by felschr** [Microsoft/VisualStudioUninstaller#55]
I'm not sure if it already works technically but I'd like to see official support for uninstalling Visual Studio 2017 RC as it somewhat destroyed my VS 2015 installation.

**Comment by heaths** [comment]
The setup experience for VS2017 will have a built-in mechanism.

As for your problem, there are a number of shared packages between 2015 and 2017. If you run http://aka.ms/vscollect.exe and attach %TEMP%\vslogs.zip to a new bug via the Feedback mechanism in 2017, we can diagnose further.
