### ISSUE TITLE
I get this error! Please help me!!

### ISSUE THREAD

**Issue by spalacio19** [Microsoft/VisualStudioUninstaller#56]
Uninstalling: C:\ProgramData\Package Cache\{1ef6a030-1244-4d01-95f3-299c0e3a3362}\vs_professional.exe
Bundle: Microsoft Visual Studio Professional 2015 has been uninstalled with exit code: 1603.
Normal Visual Studio Uninstall completed.
Searching for stale MSIs and clean up stale MSIs.
7 stale MSIs found.  Uninstalling them.
Uninstalled MS SQL Server 2012 Native Client  with exit code: 0. 6/7
Uninstalled MS SQL Server 2016 LocalDB  with exit code: 0. 5/7
Uninstalled MS SQL Server 2016 Management Objects  with exit code: 0. 4/7
Uninstalled MS SQL Server 2016 Management Objects  (x64) with exit code: 0. 3/7
Uninstalled MS SQL Server 2016 T-SQL Language Service  with exit code: 0. 2/7
Uninstalled MS SQL Server 2016 T-SQL ScriptDom  with exit code: 0. 1/7
Uninstalled VS 2015 Devenv with exit code: 1603. 0/7
Deleting: C:\ProgramData\Microsoft\VisualStudioSecondaryInstaller
Deleting registry: SOFTWARE\Microsoft\VisualStudio\12.0
Deleting registry: SOFTWARE\Microsoft\VisualStudio\14.0
Deleting registry: SOFTWARE\Microsoft\VisualStudio\15.0
Deleting registry: SOFTWARE\Microsoft\VisualStudio\12.0_Config
Deleting registry: SOFTWARE\Microsoft\VisualStudio\14.0_Config
Deleting registry: SOFTWARE\Microsoft\VisualStudio\15.0_Config
Deleting registry: SOFTWARE\Microsoft\DevDiv\vs\Servicing\12.0
Deleting registry: SOFTWARE\Microsoft\DevDiv\vs\Servicing\14.0
Deleting registry: SOFTWARE\Microsoft\DevDiv\vs\Servicing\15.0

**Comment by heaths** [comment]
That means one or more of the MSIs failed to uninstall when uninstalling the bundle, which is the first thing we do. The rest of the log shows it continued to remove things explicitly. If you run the uninstaller again it should show whether anything is actually still left.
