### ISSUE TITLE
MSVC 2017 RC Uninstall/Reinstall Cruft

### ISSUE THREAD

**Issue by mmoo9154** [Microsoft/VisualStudioUninstaller#66]
I tried to install MSVC 2017 RC on a *clean* Win10 Home x64 (v10.0.14393).  It failed because of network issues.

I uninstalled MSVC, but it left many, many subordinate pieces on my system.

I then hand deleted everything, and then deleted the `C:\Program Files (x86)\MicrosoftVisualStudio` folder.

When I tried to re-install MSVC 2017 RC using `vs_Community.exe`[1], it failed completely with a JSON deserialization error:

  `Unterminated string. Expected delimiter: ". Path 'packages[505].id', line 1, position 69223`

**Does anyone have any idea how I can clean up my inconsistent system so that Visual Studio can get through an install?**

I've attached vslogs.zip as well.

[1] MD5 Sum:  8fd207f97b559c4dd34cc835b67f15cd

**Comment by heaths** [comment]
Please use the Visual Studio Feedback tool available on the Installer. This will collect logs and other pertinent information to investigate further.

This tool is for VS2015.
