### ISSUE TITLE
Built version in github

### ISSUE THREAD

**Issue by jculverwell** [Microsoft/VisualStudioUninstaller#7]
Please could you add a prebuilt release of this to the site.  Some of us want to clean up after we have already uninstalled visula studio.

Cheers

Jim

**Comment by magol** [comment]
+1

**Comment by theBrianCui** [comment]
+1

**Comment by alphaleonis** [comment]
+1

**Comment by robvon** [comment]
+1++ Tool is useless if you need VS to compile it and VS is RIP on your machine

**Comment by gswebspace** [comment]
+1

**Comment by unitycoder** [comment]
+1

**Comment by blanthor** [comment]
+1

**Comment by josesimoes** [comment]
+1

**Comment by rent-a-developer** [comment]
+1 What purpose does a uninstaller have, if you need VS to build the uninstaller?
You most likely want to use the uninstaller to clean (and then reinstall) a broken VS installation.
At which point VS might be broken to the point where you are not able to compile the uninstaller with it...

**Comment by pirocks** [comment]
+1

**Comment by whizzkid** [comment]
+1,  I can't build it, because VS is borked and won't install properly. need to clean!
Someone please build it and add it, or post a link to the download.   It shouldn't have to take more than 3 months ?

**Comment by CADbloke** [comment]
I can't believe a pleb like me has to do this in an official Microsoft repo. .. here's a debug build in VS2015 x64 on Windows 10. Note the date of this post - there were 27 commits at the time.

# I have ~~not~~ run this ~~so there are no guarantees it will~~ it didn't work. Try it on your friend's computer first. If it eats your Windows and tweets all your nudie photos then you never saw this.

Didn't work for me on VS2013 Ultimate as per #19  Le sigh.

Moderators - you may hate this but the crowd wants it. Remember them?

[VisualStudioUninstaller.zip](https://github.com/Microsoft/VisualStudioUninstaller/files/144258/VisualStudioUninstaller.zip)

**Comment by fractalspace** [comment]
Didn't work for me. I have a truck load of crap left over by Vs2013 and 2015. Using Revo Uninstaller now (which is terribly slow when operating on MS products).

**Comment by whizzkid** [comment]
Same here, i had to install a previous image of my system drive from before VS was installed.  M$ REALLY needs to address this issue.

**Comment by DDriggs00** [comment]
Agreed, VS 2015 is not uninstalling completely (update KB2999226), and this tool did not help.

**Comment by tobyhu87** [comment]
You can find a prebuilt version of this application here:

Release link: https://github.com/Microsoft/VisualStudioUninstaller/releases
