### ISSUE TITLE
Option to uninstall which version

### ISSUE THREAD

**Issue by mstechies-zz** [Microsoft/VisualStudioUninstaller#76]
It would be nice to have options to choose which versions need to be uninstalled. Currently, this uninstalls all the previous versions starting VS 2013.

**Comment by swimtver** [comment]
+1

**Comment by heaths** [comment]
This tool removes any shared products regardless of reference counting - that is, ignoring what other products installed those shared products. As such, specifying a single version would undoubtedly leave other versions and even other products broken. This is meant to clean up failed installations. You should use the normal uninstall which will retain shared products as needed.
