### ISSUE TITLE
Need one for 2017

### ISSUE THREAD

**Issue by dylanh724** [Microsoft/VisualStudioUninstaller#77]
2017 is out - is there an uninstaller for this? VS2017 will **NOT** detect Unity Tools no matter what I do! It was working fine for a month, then out of the blue -- nope. Reinstalling both Unity 5.6f3 and VS2017 doesn't work.  :(

**Comment by tobi1449** [comment]
Similar problem here, I some remnants of the windows emulator and now I can't install a new version, an update would be great.

**Comment by ghost** [comment]
The Windows Creators update broke visual studio for me so I pretty much have to reformat. 
I wonder if this utility could've helped me.

Either way the Visual Studio unninstaller is so lazily done, it barely removes anything, there are so many leftovers, I often ended up using Geek Unninstaller but even then there are too many remains.

**Comment by ghost** [comment]
Nevermind, I found out my issue, the RivaTuner Statistics Server broke things, for some reason. I just had a little zing moment when I realized that it caused issues somehow.

Well whatever, I had to backup my files anyway and I wanted to do a clean install of the Creators Update.
Some stuff did actually bug out so it's not a big deal.

**Comment by heaths** [comment]
We have no plans at this time to support VS2017 and newer with this utility.

If properly uninstalling VS2017 does not remove all products, you can use the clean up utility that ships in VS2017. Read [here](https://developercommunity.visualstudio.com/answers/19882/view.html) for more information.
