### ISSUE TITLE
I installed Visual Studio 2015 and Visual Studio 2017, can I only uninstall VS2015?

### ISSUE THREAD

**Issue by wangwenx190** [Microsoft/VisualStudioUninstaller#78]
我的机器上装了不止一个版本的VS，卸载时能选择版本卸载而不是全部卸载吗？
I installed Visual Studio 2015 and Visual Studio 2017, can I only uninstall VS2015?

**Comment by fwd079** [comment]
> My machine installed more than one version of the VS, uninstall the version can be uninstalled instead of all uninstall?

No, sorry, it uninstalls everything.
 (  不，对不起，它卸载所有的东西。)
( 不，對不起，它卸載所有的東西。)

**Comment by heaths** [comment]
You should use the normal uninstall. Shared products are left installed, and products with a high likelihood of being required by other products are left installed as well. Uninstalling too much would break other products, and not all products participate in product ref-counting that was introduced by our team in WiX years ago to combat this.

This uninstall utility is a clean-up tool and is not meant for normal uninstall operations.
