### ISSUE TITLE
Cannot find the Setup.ForceUninstall.exe file

### ISSUE THREAD

**Issue by PostalMike** [Microsoft/VisualStudioUninstaller#80]
Downloaded the zip but there is no such critter as Setup.ForceUninstall.exe.

Why would the file be missing?  I have uniinstalled VS 2013 using the method here: https://blogs.msdn.microsoft.com/heaths/2015/07/17/removing-visual-studio-components-left-behind-after-an-uninstall/

The reason I need the forced uninstall is SSMS 2016 won't install because it tries to apply an update to VS 2015, can't do it and then rolls back.  I'm screwed without being able to install SSMS.

Background info -- About a month ago, with Windows 10 Home, updates failed to complete.  They'd get to 83% and roll back.  The Microsoft Store had to do a wipe and reload to fix the issue.

Installing apps after revealed VS 2013 is not compatible with and won't install on Windows 10.  Windows 10 upgrade can be done on a system that has VS 2013 on it but one must have 2015 or 2017.

Since the wipe and reload, there is no .exe for 2015.  So the forced uninstall from the link above won't work -- I can't find the right entries in C:\ProgramData\Package Cache\ to run the command line utility.

So ... this forced uninstall is a Godsend but ... no Setup.ForcedUninstall.exe is there.

Please let me know what's up here.

**Comment by roidy** [comment]
Wrong zip file go to Releases:-
![capture](https://cloud.githubusercontent.com/assets/4118048/25305624/d0ff9b1c-2776-11e7-9350-81e99528fb58.PNG)

Then under Release 5 you want TotalUninstaller.zip

**Comment by PostalMike** [comment]
I gave in and got VS 2015 Pro.  That solved all issues.
