### ISSUE TITLE
Will this leave VS2017 installation intact?

### ISSUE THREAD

**Issue by Dominik-H** [Microsoft/VisualStudioUninstaller#82]
Will running this uninstaller leave Visual Studio 2017 intact? I recently installed 2017 version, but since I have limited storage on my SSD I would like to delete the VS2015 without affecting VS2017 functionality? Is it allright to use in this case? Thanks.

**Comment by heaths** [comment]
Any shared products between VS2015 and VS2017 will be removed, and there are quite a few. Please note that this tool is a last resort. Uninstalling VS2015 normally will remove most components without affecting shared products.
