### ISSUE TITLE
Where is the EXE

### ISSUE THREAD

**Issue by Alpha17x** [Microsoft/VisualStudioUninstaller#88]
Is there a pre-built version of this?  I'm here because I need to blast Visual Studio off of my system. Obviously, I can't build anything with it if it's not working. ¯\_(ツ)_/¯. 'We have the solution to the problem we created. You just need to build it with the problem we created to solve the problem

**Comment by heaths** [comment]
You can find the binaries at https://github.com/Microsoft/VisualStudioUninstaller/releases.
