### ISSUE TITLE
Can't detect Visual Studio 2017 traces.

### ISSUE THREAD

**Issue by muizzsiddique** [Microsoft/VisualStudioUninstaller#90]
I forced the uninstaller (not this one) close mid-uninstall and that left some stray files and registry data to which running the new installer won't allow me to install VS 2017 in that same directory even though the folder doesn't exist. This uninstaller for some reason cannot detect VS 2017 even though the readme claims it can. What gives?

**Comment by heaths** [comment]
While the uninstall may work for some MSIs installed by Visual Studio 2017, we do not actually use many MSIs anymore. We'll look into clarifying or fixing the README.

For Visual Studio 2017, you need to run the [clean up tool](https://aka.ms/vs/cleanup). The installer for 2017 and newer is completely new.
