### ISSUE TITLE
When is it finished

### ISSUE THREAD

**Issue by JohnCHill** [Microsoft/VisualStudioUninstaller#96]
How do I know when the uninstaller is finished? It has been running for 30 minutes.

**Comment by heaths** [comment]
Uninstalling dozens of not hundreds of packages can take time. If you use the normal uninstaller (this project is for if that doesn't work - not for normal situations as this bypasses certain features to protect you from breaking Sommer other products), you get progress.

Command line control will be returned when this console app is finished.

**Comment by JohnCHill** [comment]
Thank you!
